### ISSUE TITLE
EIP-AuRa Spec Licensing 

### ISSUE THREAD

**Issue by ChainSafe** [goerli/eips-aura-spec#2]
The current AuRa spec https://wiki.parity.io/Aura.html indicates All Rights Reserved. On github https://github.com/paritytech/wiki it indicates CC-BY-SA-4.0.

**Comment by 5chdn** [comment]
We need to ask Parity authors if it's cool to have it CC0 for the EIP repository.

**Comment by 5chdn** [comment]
@rphmeier agreed making this public domain. :tada:
